// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.

package marinade_finance

import (
	"errors"
	ag_binary "github.com/gagliardetto/binary"
	ag_solanago "github.com/gagliardetto/solana-go"
	ag_format "github.com/gagliardetto/solana-go/text/format"
	ag_treeout "github.com/gagliardetto/treeout"
)

// RemoveLiquidity is the `removeLiquidity` instruction.
type RemoveLiquidity struct {
	Tokens *uint64

	// [0] = [WRITE] state
	//
	// [1] = [WRITE] lpMint
	//
	// [2] = [WRITE] burnFrom
	//
	// [3] = [SIGNER] burnFromAuthority
	//
	// [4] = [WRITE] transferSolTo
	//
	// [5] = [WRITE] transferMsolTo
	//
	// [6] = [WRITE] liqPoolSolLegPda
	//
	// [7] = [WRITE] liqPoolMsolLeg
	//
	// [8] = [] liqPoolMsolLegAuthority
	//
	// [9] = [] systemProgram
	//
	// [10] = [] tokenProgram
	ag_solanago.AccountMetaSlice `bin:"-"`
}

// NewRemoveLiquidityInstructionBuilder creates a new `RemoveLiquidity` instruction builder.
func NewRemoveLiquidityInstructionBuilder() *RemoveLiquidity {
	nd := &RemoveLiquidity{
		AccountMetaSlice: make(ag_solanago.AccountMetaSlice, 11),
	}
	return nd
}

// SetTokens sets the "tokens" parameter.
func (inst *RemoveLiquidity) SetTokens(tokens uint64) *RemoveLiquidity {
	inst.Tokens = &tokens
	return inst
}

// SetStateAccount sets the "state" account.
func (inst *RemoveLiquidity) SetStateAccount(state ag_solanago.PublicKey) *RemoveLiquidity {
	inst.AccountMetaSlice[0] = ag_solanago.Meta(state).WRITE()
	return inst
}

// GetStateAccount gets the "state" account.
func (inst *RemoveLiquidity) GetStateAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(0)
}

// SetLpMintAccount sets the "lpMint" account.
func (inst *RemoveLiquidity) SetLpMintAccount(lpMint ag_solanago.PublicKey) *RemoveLiquidity {
	inst.AccountMetaSlice[1] = ag_solanago.Meta(lpMint).WRITE()
	return inst
}

// GetLpMintAccount gets the "lpMint" account.
func (inst *RemoveLiquidity) GetLpMintAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(1)
}

// SetBurnFromAccount sets the "burnFrom" account.
func (inst *RemoveLiquidity) SetBurnFromAccount(burnFrom ag_solanago.PublicKey) *RemoveLiquidity {
	inst.AccountMetaSlice[2] = ag_solanago.Meta(burnFrom).WRITE()
	return inst
}

// GetBurnFromAccount gets the "burnFrom" account.
func (inst *RemoveLiquidity) GetBurnFromAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(2)
}

// SetBurnFromAuthorityAccount sets the "burnFromAuthority" account.
func (inst *RemoveLiquidity) SetBurnFromAuthorityAccount(burnFromAuthority ag_solanago.PublicKey) *RemoveLiquidity {
	inst.AccountMetaSlice[3] = ag_solanago.Meta(burnFromAuthority).SIGNER()
	return inst
}

// GetBurnFromAuthorityAccount gets the "burnFromAuthority" account.
func (inst *RemoveLiquidity) GetBurnFromAuthorityAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(3)
}

// SetTransferSolToAccount sets the "transferSolTo" account.
func (inst *RemoveLiquidity) SetTransferSolToAccount(transferSolTo ag_solanago.PublicKey) *RemoveLiquidity {
	inst.AccountMetaSlice[4] = ag_solanago.Meta(transferSolTo).WRITE()
	return inst
}

// GetTransferSolToAccount gets the "transferSolTo" account.
func (inst *RemoveLiquidity) GetTransferSolToAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(4)
}

// SetTransferMsolToAccount sets the "transferMsolTo" account.
func (inst *RemoveLiquidity) SetTransferMsolToAccount(transferMsolTo ag_solanago.PublicKey) *RemoveLiquidity {
	inst.AccountMetaSlice[5] = ag_solanago.Meta(transferMsolTo).WRITE()
	return inst
}

// GetTransferMsolToAccount gets the "transferMsolTo" account.
func (inst *RemoveLiquidity) GetTransferMsolToAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(5)
}

// SetLiqPoolSolLegPdaAccount sets the "liqPoolSolLegPda" account.
func (inst *RemoveLiquidity) SetLiqPoolSolLegPdaAccount(liqPoolSolLegPda ag_solanago.PublicKey) *RemoveLiquidity {
	inst.AccountMetaSlice[6] = ag_solanago.Meta(liqPoolSolLegPda).WRITE()
	return inst
}

// GetLiqPoolSolLegPdaAccount gets the "liqPoolSolLegPda" account.
func (inst *RemoveLiquidity) GetLiqPoolSolLegPdaAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(6)
}

// SetLiqPoolMsolLegAccount sets the "liqPoolMsolLeg" account.
func (inst *RemoveLiquidity) SetLiqPoolMsolLegAccount(liqPoolMsolLeg ag_solanago.PublicKey) *RemoveLiquidity {
	inst.AccountMetaSlice[7] = ag_solanago.Meta(liqPoolMsolLeg).WRITE()
	return inst
}

// GetLiqPoolMsolLegAccount gets the "liqPoolMsolLeg" account.
func (inst *RemoveLiquidity) GetLiqPoolMsolLegAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(7)
}

// SetLiqPoolMsolLegAuthorityAccount sets the "liqPoolMsolLegAuthority" account.
func (inst *RemoveLiquidity) SetLiqPoolMsolLegAuthorityAccount(liqPoolMsolLegAuthority ag_solanago.PublicKey) *RemoveLiquidity {
	inst.AccountMetaSlice[8] = ag_solanago.Meta(liqPoolMsolLegAuthority)
	return inst
}

// GetLiqPoolMsolLegAuthorityAccount gets the "liqPoolMsolLegAuthority" account.
func (inst *RemoveLiquidity) GetLiqPoolMsolLegAuthorityAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(8)
}

// SetSystemProgramAccount sets the "systemProgram" account.
func (inst *RemoveLiquidity) SetSystemProgramAccount(systemProgram ag_solanago.PublicKey) *RemoveLiquidity {
	inst.AccountMetaSlice[9] = ag_solanago.Meta(systemProgram)
	return inst
}

// GetSystemProgramAccount gets the "systemProgram" account.
func (inst *RemoveLiquidity) GetSystemProgramAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(9)
}

// SetTokenProgramAccount sets the "tokenProgram" account.
func (inst *RemoveLiquidity) SetTokenProgramAccount(tokenProgram ag_solanago.PublicKey) *RemoveLiquidity {
	inst.AccountMetaSlice[10] = ag_solanago.Meta(tokenProgram)
	return inst
}

// GetTokenProgramAccount gets the "tokenProgram" account.
func (inst *RemoveLiquidity) GetTokenProgramAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(10)
}

func (inst RemoveLiquidity) Build() *Instruction {
	return &Instruction{BaseVariant: ag_binary.BaseVariant{
		Impl:   inst,
		TypeID: Instruction_RemoveLiquidity,
	}}
}

// ValidateAndBuild validates the instruction parameters and accounts;
// if there is a validation error, it returns the error.
// Otherwise, it builds and returns the instruction.
func (inst RemoveLiquidity) ValidateAndBuild() (*Instruction, error) {
	if err := inst.Validate(); err != nil {
		return nil, err
	}
	return inst.Build(), nil
}

func (inst *RemoveLiquidity) Validate() error {
	// Check whether all (required) parameters are set:
	{
		if inst.Tokens == nil {
			return errors.New("Tokens parameter is not set")
		}
	}

	// Check whether all (required) accounts are set:
	{
		if inst.AccountMetaSlice[0] == nil {
			return errors.New("accounts.State is not set")
		}
		if inst.AccountMetaSlice[1] == nil {
			return errors.New("accounts.LpMint is not set")
		}
		if inst.AccountMetaSlice[2] == nil {
			return errors.New("accounts.BurnFrom is not set")
		}
		if inst.AccountMetaSlice[3] == nil {
			return errors.New("accounts.BurnFromAuthority is not set")
		}
		if inst.AccountMetaSlice[4] == nil {
			return errors.New("accounts.TransferSolTo is not set")
		}
		if inst.AccountMetaSlice[5] == nil {
			return errors.New("accounts.TransferMsolTo is not set")
		}
		if inst.AccountMetaSlice[6] == nil {
			return errors.New("accounts.LiqPoolSolLegPda is not set")
		}
		if inst.AccountMetaSlice[7] == nil {
			return errors.New("accounts.LiqPoolMsolLeg is not set")
		}
		if inst.AccountMetaSlice[8] == nil {
			return errors.New("accounts.LiqPoolMsolLegAuthority is not set")
		}
		if inst.AccountMetaSlice[9] == nil {
			return errors.New("accounts.SystemProgram is not set")
		}
		if inst.AccountMetaSlice[10] == nil {
			return errors.New("accounts.TokenProgram is not set")
		}
	}
	return nil
}

func (inst *RemoveLiquidity) EncodeToTree(parent ag_treeout.Branches) {
	parent.Child(ag_format.Program(ProgramName, ProgramID)).
		//
		ParentFunc(func(programBranch ag_treeout.Branches) {
			programBranch.Child(ag_format.Instruction("RemoveLiquidity")).
				//
				ParentFunc(func(instructionBranch ag_treeout.Branches) {

					// Parameters of the instruction:
					instructionBranch.Child("Params[len=1]").ParentFunc(func(paramsBranch ag_treeout.Branches) {
						paramsBranch.Child(ag_format.Param("Tokens", *inst.Tokens))
					})

					// Accounts of the instruction:
					instructionBranch.Child("Accounts[len=11]").ParentFunc(func(accountsBranch ag_treeout.Branches) {
						accountsBranch.Child(ag_format.Meta("                  state", inst.AccountMetaSlice.Get(0)))
						accountsBranch.Child(ag_format.Meta("                 lpMint", inst.AccountMetaSlice.Get(1)))
						accountsBranch.Child(ag_format.Meta("               burnFrom", inst.AccountMetaSlice.Get(2)))
						accountsBranch.Child(ag_format.Meta("      burnFromAuthority", inst.AccountMetaSlice.Get(3)))
						accountsBranch.Child(ag_format.Meta("          transferSolTo", inst.AccountMetaSlice.Get(4)))
						accountsBranch.Child(ag_format.Meta("         transferMsolTo", inst.AccountMetaSlice.Get(5)))
						accountsBranch.Child(ag_format.Meta("       liqPoolSolLegPda", inst.AccountMetaSlice.Get(6)))
						accountsBranch.Child(ag_format.Meta("         liqPoolMsolLeg", inst.AccountMetaSlice.Get(7)))
						accountsBranch.Child(ag_format.Meta("liqPoolMsolLegAuthority", inst.AccountMetaSlice.Get(8)))
						accountsBranch.Child(ag_format.Meta("          systemProgram", inst.AccountMetaSlice.Get(9)))
						accountsBranch.Child(ag_format.Meta("           tokenProgram", inst.AccountMetaSlice.Get(10)))
					})
				})
		})
}

func (obj RemoveLiquidity) MarshalWithEncoder(encoder *ag_binary.Encoder) (err error) {
	// Serialize `Tokens` param:
	err = encoder.Encode(obj.Tokens)
	if err != nil {
		return err
	}
	return nil
}
func (obj *RemoveLiquidity) UnmarshalWithDecoder(decoder *ag_binary.Decoder) (err error) {
	// Deserialize `Tokens`:
	err = decoder.Decode(&obj.Tokens)
	if err != nil {
		return err
	}
	return nil
}

// NewRemoveLiquidityInstruction declares a new RemoveLiquidity instruction with the provided parameters and accounts.
func NewRemoveLiquidityInstruction(
	// Parameters:
	tokens uint64,
	// Accounts:
	state ag_solanago.PublicKey,
	lpMint ag_solanago.PublicKey,
	burnFrom ag_solanago.PublicKey,
	burnFromAuthority ag_solanago.PublicKey,
	transferSolTo ag_solanago.PublicKey,
	transferMsolTo ag_solanago.PublicKey,
	liqPoolSolLegPda ag_solanago.PublicKey,
	liqPoolMsolLeg ag_solanago.PublicKey,
	liqPoolMsolLegAuthority ag_solanago.PublicKey,
	systemProgram ag_solanago.PublicKey,
	tokenProgram ag_solanago.PublicKey) *RemoveLiquidity {
	return NewRemoveLiquidityInstructionBuilder().
		SetTokens(tokens).
		SetStateAccount(state).
		SetLpMintAccount(lpMint).
		SetBurnFromAccount(burnFrom).
		SetBurnFromAuthorityAccount(burnFromAuthority).
		SetTransferSolToAccount(transferSolTo).
		SetTransferMsolToAccount(transferMsolTo).
		SetLiqPoolSolLegPdaAccount(liqPoolSolLegPda).
		SetLiqPoolMsolLegAccount(liqPoolMsolLeg).
		SetLiqPoolMsolLegAuthorityAccount(liqPoolMsolLegAuthority).
		SetSystemProgramAccount(systemProgram).
		SetTokenProgramAccount(tokenProgram)
}
