// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.

package marinade_finance

import (
	"errors"
	ag_binary "github.com/gagliardetto/binary"
	ag_solanago "github.com/gagliardetto/solana-go"
	ag_format "github.com/gagliardetto/solana-go/text/format"
	ag_treeout "github.com/gagliardetto/treeout"
)

// SetValidatorScore is the `setValidatorScore` instruction.
type SetValidatorScore struct {
	Index         *uint32
	ValidatorVote *ag_solanago.PublicKey
	Score         *uint32

	// [0] = [WRITE] state
	//
	// [1] = [SIGNER] managerAuthority
	//
	// [2] = [WRITE] validatorList
	ag_solanago.AccountMetaSlice `bin:"-"`
}

// NewSetValidatorScoreInstructionBuilder creates a new `SetValidatorScore` instruction builder.
func NewSetValidatorScoreInstructionBuilder() *SetValidatorScore {
	nd := &SetValidatorScore{
		AccountMetaSlice: make(ag_solanago.AccountMetaSlice, 3),
	}
	return nd
}

// SetIndex sets the "index" parameter.
func (inst *SetValidatorScore) SetIndex(index uint32) *SetValidatorScore {
	inst.Index = &index
	return inst
}

// SetValidatorVote sets the "validatorVote" parameter.
func (inst *SetValidatorScore) SetValidatorVote(validatorVote ag_solanago.PublicKey) *SetValidatorScore {
	inst.ValidatorVote = &validatorVote
	return inst
}

// SetScore sets the "score" parameter.
func (inst *SetValidatorScore) SetScore(score uint32) *SetValidatorScore {
	inst.Score = &score
	return inst
}

// SetStateAccount sets the "state" account.
func (inst *SetValidatorScore) SetStateAccount(state ag_solanago.PublicKey) *SetValidatorScore {
	inst.AccountMetaSlice[0] = ag_solanago.Meta(state).WRITE()
	return inst
}

// GetStateAccount gets the "state" account.
func (inst *SetValidatorScore) GetStateAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(0)
}

// SetManagerAuthorityAccount sets the "managerAuthority" account.
func (inst *SetValidatorScore) SetManagerAuthorityAccount(managerAuthority ag_solanago.PublicKey) *SetValidatorScore {
	inst.AccountMetaSlice[1] = ag_solanago.Meta(managerAuthority).SIGNER()
	return inst
}

// GetManagerAuthorityAccount gets the "managerAuthority" account.
func (inst *SetValidatorScore) GetManagerAuthorityAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(1)
}

// SetValidatorListAccount sets the "validatorList" account.
func (inst *SetValidatorScore) SetValidatorListAccount(validatorList ag_solanago.PublicKey) *SetValidatorScore {
	inst.AccountMetaSlice[2] = ag_solanago.Meta(validatorList).WRITE()
	return inst
}

// GetValidatorListAccount gets the "validatorList" account.
func (inst *SetValidatorScore) GetValidatorListAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(2)
}

func (inst SetValidatorScore) Build() *Instruction {
	return &Instruction{BaseVariant: ag_binary.BaseVariant{
		Impl:   inst,
		TypeID: Instruction_SetValidatorScore,
	}}
}

// ValidateAndBuild validates the instruction parameters and accounts;
// if there is a validation error, it returns the error.
// Otherwise, it builds and returns the instruction.
func (inst SetValidatorScore) ValidateAndBuild() (*Instruction, error) {
	if err := inst.Validate(); err != nil {
		return nil, err
	}
	return inst.Build(), nil
}

func (inst *SetValidatorScore) Validate() error {
	// Check whether all (required) parameters are set:
	{
		if inst.Index == nil {
			return errors.New("Index parameter is not set")
		}
		if inst.ValidatorVote == nil {
			return errors.New("ValidatorVote parameter is not set")
		}
		if inst.Score == nil {
			return errors.New("Score parameter is not set")
		}
	}

	// Check whether all (required) accounts are set:
	{
		if inst.AccountMetaSlice[0] == nil {
			return errors.New("accounts.State is not set")
		}
		if inst.AccountMetaSlice[1] == nil {
			return errors.New("accounts.ManagerAuthority is not set")
		}
		if inst.AccountMetaSlice[2] == nil {
			return errors.New("accounts.ValidatorList is not set")
		}
	}
	return nil
}

func (inst *SetValidatorScore) EncodeToTree(parent ag_treeout.Branches) {
	parent.Child(ag_format.Program(ProgramName, ProgramID)).
		//
		ParentFunc(func(programBranch ag_treeout.Branches) {
			programBranch.Child(ag_format.Instruction("SetValidatorScore")).
				//
				ParentFunc(func(instructionBranch ag_treeout.Branches) {

					// Parameters of the instruction:
					instructionBranch.Child("Params[len=3]").ParentFunc(func(paramsBranch ag_treeout.Branches) {
						paramsBranch.Child(ag_format.Param("        Index", *inst.Index))
						paramsBranch.Child(ag_format.Param("ValidatorVote", *inst.ValidatorVote))
						paramsBranch.Child(ag_format.Param("        Score", *inst.Score))
					})

					// Accounts of the instruction:
					instructionBranch.Child("Accounts[len=3]").ParentFunc(func(accountsBranch ag_treeout.Branches) {
						accountsBranch.Child(ag_format.Meta("           state", inst.AccountMetaSlice.Get(0)))
						accountsBranch.Child(ag_format.Meta("managerAuthority", inst.AccountMetaSlice.Get(1)))
						accountsBranch.Child(ag_format.Meta("   validatorList", inst.AccountMetaSlice.Get(2)))
					})
				})
		})
}

func (obj SetValidatorScore) MarshalWithEncoder(encoder *ag_binary.Encoder) (err error) {
	// Serialize `Index` param:
	err = encoder.Encode(obj.Index)
	if err != nil {
		return err
	}
	// Serialize `ValidatorVote` param:
	err = encoder.Encode(obj.ValidatorVote)
	if err != nil {
		return err
	}
	// Serialize `Score` param:
	err = encoder.Encode(obj.Score)
	if err != nil {
		return err
	}
	return nil
}
func (obj *SetValidatorScore) UnmarshalWithDecoder(decoder *ag_binary.Decoder) (err error) {
	// Deserialize `Index`:
	err = decoder.Decode(&obj.Index)
	if err != nil {
		return err
	}
	// Deserialize `ValidatorVote`:
	err = decoder.Decode(&obj.ValidatorVote)
	if err != nil {
		return err
	}
	// Deserialize `Score`:
	err = decoder.Decode(&obj.Score)
	if err != nil {
		return err
	}
	return nil
}

// NewSetValidatorScoreInstruction declares a new SetValidatorScore instruction with the provided parameters and accounts.
func NewSetValidatorScoreInstruction(
	// Parameters:
	index uint32,
	validatorVote ag_solanago.PublicKey,
	score uint32,
	// Accounts:
	state ag_solanago.PublicKey,
	managerAuthority ag_solanago.PublicKey,
	validatorList ag_solanago.PublicKey) *SetValidatorScore {
	return NewSetValidatorScoreInstructionBuilder().
		SetIndex(index).
		SetValidatorVote(validatorVote).
		SetScore(score).
		SetStateAccount(state).
		SetManagerAuthorityAccount(managerAuthority).
		SetValidatorListAccount(validatorList)
}
