// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.

package marinade_finance

import (
	"errors"
	ag_binary "github.com/gagliardetto/binary"
	ag_solanago "github.com/gagliardetto/solana-go"
	ag_format "github.com/gagliardetto/solana-go/text/format"
	ag_treeout "github.com/gagliardetto/treeout"
)

// StakeReserve is the `stakeReserve` instruction.
type StakeReserve struct {
	ValidatorIndex *uint32

	// [0] = [WRITE] state
	//
	// [1] = [WRITE] validatorList
	//
	// [2] = [WRITE] stakeList
	//
	// [3] = [WRITE] validatorVote
	//
	// [4] = [WRITE] reservePda
	//
	// [5] = [WRITE, SIGNER] stakeAccount
	//
	// [6] = [] stakeDepositAuthority
	//
	// [7] = [WRITE, SIGNER] rentPayer
	//
	// [8] = [] clock
	//
	// [9] = [] epochSchedule
	//
	// [10] = [] rent
	//
	// [11] = [] stakeHistory
	//
	// [12] = [] stakeConfig
	//
	// [13] = [] systemProgram
	//
	// [14] = [] stakeProgram
	ag_solanago.AccountMetaSlice `bin:"-"`
}

// NewStakeReserveInstructionBuilder creates a new `StakeReserve` instruction builder.
func NewStakeReserveInstructionBuilder() *StakeReserve {
	nd := &StakeReserve{
		AccountMetaSlice: make(ag_solanago.AccountMetaSlice, 15),
	}
	return nd
}

// SetValidatorIndex sets the "validatorIndex" parameter.
func (inst *StakeReserve) SetValidatorIndex(validatorIndex uint32) *StakeReserve {
	inst.ValidatorIndex = &validatorIndex
	return inst
}

// SetStateAccount sets the "state" account.
func (inst *StakeReserve) SetStateAccount(state ag_solanago.PublicKey) *StakeReserve {
	inst.AccountMetaSlice[0] = ag_solanago.Meta(state).WRITE()
	return inst
}

// GetStateAccount gets the "state" account.
func (inst *StakeReserve) GetStateAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(0)
}

// SetValidatorListAccount sets the "validatorList" account.
func (inst *StakeReserve) SetValidatorListAccount(validatorList ag_solanago.PublicKey) *StakeReserve {
	inst.AccountMetaSlice[1] = ag_solanago.Meta(validatorList).WRITE()
	return inst
}

// GetValidatorListAccount gets the "validatorList" account.
func (inst *StakeReserve) GetValidatorListAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(1)
}

// SetStakeListAccount sets the "stakeList" account.
func (inst *StakeReserve) SetStakeListAccount(stakeList ag_solanago.PublicKey) *StakeReserve {
	inst.AccountMetaSlice[2] = ag_solanago.Meta(stakeList).WRITE()
	return inst
}

// GetStakeListAccount gets the "stakeList" account.
func (inst *StakeReserve) GetStakeListAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(2)
}

// SetValidatorVoteAccount sets the "validatorVote" account.
func (inst *StakeReserve) SetValidatorVoteAccount(validatorVote ag_solanago.PublicKey) *StakeReserve {
	inst.AccountMetaSlice[3] = ag_solanago.Meta(validatorVote).WRITE()
	return inst
}

// GetValidatorVoteAccount gets the "validatorVote" account.
func (inst *StakeReserve) GetValidatorVoteAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(3)
}

// SetReservePdaAccount sets the "reservePda" account.
func (inst *StakeReserve) SetReservePdaAccount(reservePda ag_solanago.PublicKey) *StakeReserve {
	inst.AccountMetaSlice[4] = ag_solanago.Meta(reservePda).WRITE()
	return inst
}

// GetReservePdaAccount gets the "reservePda" account.
func (inst *StakeReserve) GetReservePdaAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(4)
}

// SetStakeAccountAccount sets the "stakeAccount" account.
func (inst *StakeReserve) SetStakeAccountAccount(stakeAccount ag_solanago.PublicKey) *StakeReserve {
	inst.AccountMetaSlice[5] = ag_solanago.Meta(stakeAccount).WRITE().SIGNER()
	return inst
}

// GetStakeAccountAccount gets the "stakeAccount" account.
func (inst *StakeReserve) GetStakeAccountAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(5)
}

// SetStakeDepositAuthorityAccount sets the "stakeDepositAuthority" account.
func (inst *StakeReserve) SetStakeDepositAuthorityAccount(stakeDepositAuthority ag_solanago.PublicKey) *StakeReserve {
	inst.AccountMetaSlice[6] = ag_solanago.Meta(stakeDepositAuthority)
	return inst
}

// GetStakeDepositAuthorityAccount gets the "stakeDepositAuthority" account.
func (inst *StakeReserve) GetStakeDepositAuthorityAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(6)
}

// SetRentPayerAccount sets the "rentPayer" account.
func (inst *StakeReserve) SetRentPayerAccount(rentPayer ag_solanago.PublicKey) *StakeReserve {
	inst.AccountMetaSlice[7] = ag_solanago.Meta(rentPayer).WRITE().SIGNER()
	return inst
}

// GetRentPayerAccount gets the "rentPayer" account.
func (inst *StakeReserve) GetRentPayerAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(7)
}

// SetClockAccount sets the "clock" account.
func (inst *StakeReserve) SetClockAccount(clock ag_solanago.PublicKey) *StakeReserve {
	inst.AccountMetaSlice[8] = ag_solanago.Meta(clock)
	return inst
}

// GetClockAccount gets the "clock" account.
func (inst *StakeReserve) GetClockAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(8)
}

// SetEpochScheduleAccount sets the "epochSchedule" account.
func (inst *StakeReserve) SetEpochScheduleAccount(epochSchedule ag_solanago.PublicKey) *StakeReserve {
	inst.AccountMetaSlice[9] = ag_solanago.Meta(epochSchedule)
	return inst
}

// GetEpochScheduleAccount gets the "epochSchedule" account.
func (inst *StakeReserve) GetEpochScheduleAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(9)
}

// SetRentAccount sets the "rent" account.
func (inst *StakeReserve) SetRentAccount(rent ag_solanago.PublicKey) *StakeReserve {
	inst.AccountMetaSlice[10] = ag_solanago.Meta(rent)
	return inst
}

// GetRentAccount gets the "rent" account.
func (inst *StakeReserve) GetRentAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(10)
}

// SetStakeHistoryAccount sets the "stakeHistory" account.
func (inst *StakeReserve) SetStakeHistoryAccount(stakeHistory ag_solanago.PublicKey) *StakeReserve {
	inst.AccountMetaSlice[11] = ag_solanago.Meta(stakeHistory)
	return inst
}

// GetStakeHistoryAccount gets the "stakeHistory" account.
func (inst *StakeReserve) GetStakeHistoryAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(11)
}

// SetStakeConfigAccount sets the "stakeConfig" account.
func (inst *StakeReserve) SetStakeConfigAccount(stakeConfig ag_solanago.PublicKey) *StakeReserve {
	inst.AccountMetaSlice[12] = ag_solanago.Meta(stakeConfig)
	return inst
}

// GetStakeConfigAccount gets the "stakeConfig" account.
func (inst *StakeReserve) GetStakeConfigAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(12)
}

// SetSystemProgramAccount sets the "systemProgram" account.
func (inst *StakeReserve) SetSystemProgramAccount(systemProgram ag_solanago.PublicKey) *StakeReserve {
	inst.AccountMetaSlice[13] = ag_solanago.Meta(systemProgram)
	return inst
}

// GetSystemProgramAccount gets the "systemProgram" account.
func (inst *StakeReserve) GetSystemProgramAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(13)
}

// SetStakeProgramAccount sets the "stakeProgram" account.
func (inst *StakeReserve) SetStakeProgramAccount(stakeProgram ag_solanago.PublicKey) *StakeReserve {
	inst.AccountMetaSlice[14] = ag_solanago.Meta(stakeProgram)
	return inst
}

// GetStakeProgramAccount gets the "stakeProgram" account.
func (inst *StakeReserve) GetStakeProgramAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(14)
}

func (inst StakeReserve) Build() *Instruction {
	return &Instruction{BaseVariant: ag_binary.BaseVariant{
		Impl:   inst,
		TypeID: Instruction_StakeReserve,
	}}
}

// ValidateAndBuild validates the instruction parameters and accounts;
// if there is a validation error, it returns the error.
// Otherwise, it builds and returns the instruction.
func (inst StakeReserve) ValidateAndBuild() (*Instruction, error) {
	if err := inst.Validate(); err != nil {
		return nil, err
	}
	return inst.Build(), nil
}

func (inst *StakeReserve) Validate() error {
	// Check whether all (required) parameters are set:
	{
		if inst.ValidatorIndex == nil {
			return errors.New("ValidatorIndex parameter is not set")
		}
	}

	// Check whether all (required) accounts are set:
	{
		if inst.AccountMetaSlice[0] == nil {
			return errors.New("accounts.State is not set")
		}
		if inst.AccountMetaSlice[1] == nil {
			return errors.New("accounts.ValidatorList is not set")
		}
		if inst.AccountMetaSlice[2] == nil {
			return errors.New("accounts.StakeList is not set")
		}
		if inst.AccountMetaSlice[3] == nil {
			return errors.New("accounts.ValidatorVote is not set")
		}
		if inst.AccountMetaSlice[4] == nil {
			return errors.New("accounts.ReservePda is not set")
		}
		if inst.AccountMetaSlice[5] == nil {
			return errors.New("accounts.StakeAccount is not set")
		}
		if inst.AccountMetaSlice[6] == nil {
			return errors.New("accounts.StakeDepositAuthority is not set")
		}
		if inst.AccountMetaSlice[7] == nil {
			return errors.New("accounts.RentPayer is not set")
		}
		if inst.AccountMetaSlice[8] == nil {
			return errors.New("accounts.Clock is not set")
		}
		if inst.AccountMetaSlice[9] == nil {
			return errors.New("accounts.EpochSchedule is not set")
		}
		if inst.AccountMetaSlice[10] == nil {
			return errors.New("accounts.Rent is not set")
		}
		if inst.AccountMetaSlice[11] == nil {
			return errors.New("accounts.StakeHistory is not set")
		}
		if inst.AccountMetaSlice[12] == nil {
			return errors.New("accounts.StakeConfig is not set")
		}
		if inst.AccountMetaSlice[13] == nil {
			return errors.New("accounts.SystemProgram is not set")
		}
		if inst.AccountMetaSlice[14] == nil {
			return errors.New("accounts.StakeProgram is not set")
		}
	}
	return nil
}

func (inst *StakeReserve) EncodeToTree(parent ag_treeout.Branches) {
	parent.Child(ag_format.Program(ProgramName, ProgramID)).
		//
		ParentFunc(func(programBranch ag_treeout.Branches) {
			programBranch.Child(ag_format.Instruction("StakeReserve")).
				//
				ParentFunc(func(instructionBranch ag_treeout.Branches) {

					// Parameters of the instruction:
					instructionBranch.Child("Params[len=1]").ParentFunc(func(paramsBranch ag_treeout.Branches) {
						paramsBranch.Child(ag_format.Param("ValidatorIndex", *inst.ValidatorIndex))
					})

					// Accounts of the instruction:
					instructionBranch.Child("Accounts[len=15]").ParentFunc(func(accountsBranch ag_treeout.Branches) {
						accountsBranch.Child(ag_format.Meta("                state", inst.AccountMetaSlice.Get(0)))
						accountsBranch.Child(ag_format.Meta("        validatorList", inst.AccountMetaSlice.Get(1)))
						accountsBranch.Child(ag_format.Meta("            stakeList", inst.AccountMetaSlice.Get(2)))
						accountsBranch.Child(ag_format.Meta("        validatorVote", inst.AccountMetaSlice.Get(3)))
						accountsBranch.Child(ag_format.Meta("           reservePda", inst.AccountMetaSlice.Get(4)))
						accountsBranch.Child(ag_format.Meta("                stake", inst.AccountMetaSlice.Get(5)))
						accountsBranch.Child(ag_format.Meta("stakeDepositAuthority", inst.AccountMetaSlice.Get(6)))
						accountsBranch.Child(ag_format.Meta("            rentPayer", inst.AccountMetaSlice.Get(7)))
						accountsBranch.Child(ag_format.Meta("                clock", inst.AccountMetaSlice.Get(8)))
						accountsBranch.Child(ag_format.Meta("        epochSchedule", inst.AccountMetaSlice.Get(9)))
						accountsBranch.Child(ag_format.Meta("                 rent", inst.AccountMetaSlice.Get(10)))
						accountsBranch.Child(ag_format.Meta("         stakeHistory", inst.AccountMetaSlice.Get(11)))
						accountsBranch.Child(ag_format.Meta("          stakeConfig", inst.AccountMetaSlice.Get(12)))
						accountsBranch.Child(ag_format.Meta("        systemProgram", inst.AccountMetaSlice.Get(13)))
						accountsBranch.Child(ag_format.Meta("         stakeProgram", inst.AccountMetaSlice.Get(14)))
					})
				})
		})
}

func (obj StakeReserve) MarshalWithEncoder(encoder *ag_binary.Encoder) (err error) {
	// Serialize `ValidatorIndex` param:
	err = encoder.Encode(obj.ValidatorIndex)
	if err != nil {
		return err
	}
	return nil
}
func (obj *StakeReserve) UnmarshalWithDecoder(decoder *ag_binary.Decoder) (err error) {
	// Deserialize `ValidatorIndex`:
	err = decoder.Decode(&obj.ValidatorIndex)
	if err != nil {
		return err
	}
	return nil
}

// NewStakeReserveInstruction declares a new StakeReserve instruction with the provided parameters and accounts.
func NewStakeReserveInstruction(
	// Parameters:
	validatorIndex uint32,
	// Accounts:
	state ag_solanago.PublicKey,
	validatorList ag_solanago.PublicKey,
	stakeList ag_solanago.PublicKey,
	validatorVote ag_solanago.PublicKey,
	reservePda ag_solanago.PublicKey,
	stakeAccount ag_solanago.PublicKey,
	stakeDepositAuthority ag_solanago.PublicKey,
	rentPayer ag_solanago.PublicKey,
	clock ag_solanago.PublicKey,
	epochSchedule ag_solanago.PublicKey,
	rent ag_solanago.PublicKey,
	stakeHistory ag_solanago.PublicKey,
	stakeConfig ag_solanago.PublicKey,
	systemProgram ag_solanago.PublicKey,
	stakeProgram ag_solanago.PublicKey) *StakeReserve {
	return NewStakeReserveInstructionBuilder().
		SetValidatorIndex(validatorIndex).
		SetStateAccount(state).
		SetValidatorListAccount(validatorList).
		SetStakeListAccount(stakeList).
		SetValidatorVoteAccount(validatorVote).
		SetReservePdaAccount(reservePda).
		SetStakeAccountAccount(stakeAccount).
		SetStakeDepositAuthorityAccount(stakeDepositAuthority).
		SetRentPayerAccount(rentPayer).
		SetClockAccount(clock).
		SetEpochScheduleAccount(epochSchedule).
		SetRentAccount(rent).
		SetStakeHistoryAccount(stakeHistory).
		SetStakeConfigAccount(stakeConfig).
		SetSystemProgramAccount(systemProgram).
		SetStakeProgramAccount(stakeProgram)
}
