// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.

package marinade_finance

import (
	"errors"
	ag_binary "github.com/gagliardetto/binary"
	ag_solanago "github.com/gagliardetto/solana-go"
	ag_format "github.com/gagliardetto/solana-go/text/format"
	ag_treeout "github.com/gagliardetto/treeout"
)

// UpdateDeactivated is the `updateDeactivated` instruction.
type UpdateDeactivated struct {
	StakeIndex *uint32

	// ····· common: [0] = [WRITE] state
	//
	// ············· [1] = [WRITE] stakeList
	//
	// ············· [2] = [WRITE] stakeAccount
	//
	// ············· [3] = [] stakeWithdrawAuthority
	//
	// ············· [4] = [WRITE] reservePda
	//
	// ············· [5] = [WRITE] msolMint
	//
	// ············· [6] = [] msolMintAuthority
	//
	// ············· [7] = [WRITE] treasuryMsolAccount
	//
	// ············· [8] = [] clock
	//
	// ············· [9] = [] stakeHistory
	//
	// ············· [10] = [] stakeProgram
	//
	// ············· [11] = [] tokenProgram
	//
	// [12] = [WRITE] operationalSolAccount
	//
	// [13] = [] systemProgram
	ag_solanago.AccountMetaSlice `bin:"-"`
}

// NewUpdateDeactivatedInstructionBuilder creates a new `UpdateDeactivated` instruction builder.
func NewUpdateDeactivatedInstructionBuilder() *UpdateDeactivated {
	nd := &UpdateDeactivated{
		AccountMetaSlice: make(ag_solanago.AccountMetaSlice, 14),
	}
	return nd
}

// SetStakeIndex sets the "stakeIndex" parameter.
func (inst *UpdateDeactivated) SetStakeIndex(stakeIndex uint32) *UpdateDeactivated {
	inst.StakeIndex = &stakeIndex
	return inst
}

type UpdateDeactivatedCommonAccountsBuilder struct {
	ag_solanago.AccountMetaSlice `bin:"-"`
}

func NewUpdateDeactivatedCommonAccountsBuilder() *UpdateDeactivatedCommonAccountsBuilder {
	return &UpdateDeactivatedCommonAccountsBuilder{
		AccountMetaSlice: make(ag_solanago.AccountMetaSlice, 12),
	}
}

func (inst *UpdateDeactivated) SetCommonAccountsFromBuilder(updateDeactivatedCommonAccountsBuilder *UpdateDeactivatedCommonAccountsBuilder) *UpdateDeactivated {
	inst.AccountMetaSlice[0] = updateDeactivatedCommonAccountsBuilder.GetStateAccount()
	inst.AccountMetaSlice[1] = updateDeactivatedCommonAccountsBuilder.GetStakeListAccount()
	inst.AccountMetaSlice[2] = updateDeactivatedCommonAccountsBuilder.GetStakeAccountAccount()
	inst.AccountMetaSlice[3] = updateDeactivatedCommonAccountsBuilder.GetStakeWithdrawAuthorityAccount()
	inst.AccountMetaSlice[4] = updateDeactivatedCommonAccountsBuilder.GetReservePdaAccount()
	inst.AccountMetaSlice[5] = updateDeactivatedCommonAccountsBuilder.GetMsolMintAccount()
	inst.AccountMetaSlice[6] = updateDeactivatedCommonAccountsBuilder.GetMsolMintAuthorityAccount()
	inst.AccountMetaSlice[7] = updateDeactivatedCommonAccountsBuilder.GetTreasuryMsolAccountAccount()
	inst.AccountMetaSlice[8] = updateDeactivatedCommonAccountsBuilder.GetClockAccount()
	inst.AccountMetaSlice[9] = updateDeactivatedCommonAccountsBuilder.GetStakeHistoryAccount()
	inst.AccountMetaSlice[10] = updateDeactivatedCommonAccountsBuilder.GetStakeProgramAccount()
	inst.AccountMetaSlice[11] = updateDeactivatedCommonAccountsBuilder.GetTokenProgramAccount()
	return inst
}

// SetStateAccount sets the "state" account.
func (inst *UpdateDeactivatedCommonAccountsBuilder) SetStateAccount(state ag_solanago.PublicKey) *UpdateDeactivatedCommonAccountsBuilder {
	inst.AccountMetaSlice[0] = ag_solanago.Meta(state).WRITE()
	return inst
}

// GetStateAccount gets the "state" account.
func (inst *UpdateDeactivatedCommonAccountsBuilder) GetStateAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(0)
}

// SetStakeListAccount sets the "stakeList" account.
func (inst *UpdateDeactivatedCommonAccountsBuilder) SetStakeListAccount(stakeList ag_solanago.PublicKey) *UpdateDeactivatedCommonAccountsBuilder {
	inst.AccountMetaSlice[1] = ag_solanago.Meta(stakeList).WRITE()
	return inst
}

// GetStakeListAccount gets the "stakeList" account.
func (inst *UpdateDeactivatedCommonAccountsBuilder) GetStakeListAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(1)
}

// SetStakeAccountAccount sets the "stakeAccount" account.
func (inst *UpdateDeactivatedCommonAccountsBuilder) SetStakeAccountAccount(stakeAccount ag_solanago.PublicKey) *UpdateDeactivatedCommonAccountsBuilder {
	inst.AccountMetaSlice[2] = ag_solanago.Meta(stakeAccount).WRITE()
	return inst
}

// GetStakeAccountAccount gets the "stakeAccount" account.
func (inst *UpdateDeactivatedCommonAccountsBuilder) GetStakeAccountAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(2)
}

// SetStakeWithdrawAuthorityAccount sets the "stakeWithdrawAuthority" account.
func (inst *UpdateDeactivatedCommonAccountsBuilder) SetStakeWithdrawAuthorityAccount(stakeWithdrawAuthority ag_solanago.PublicKey) *UpdateDeactivatedCommonAccountsBuilder {
	inst.AccountMetaSlice[3] = ag_solanago.Meta(stakeWithdrawAuthority)
	return inst
}

// GetStakeWithdrawAuthorityAccount gets the "stakeWithdrawAuthority" account.
func (inst *UpdateDeactivatedCommonAccountsBuilder) GetStakeWithdrawAuthorityAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(3)
}

// SetReservePdaAccount sets the "reservePda" account.
func (inst *UpdateDeactivatedCommonAccountsBuilder) SetReservePdaAccount(reservePda ag_solanago.PublicKey) *UpdateDeactivatedCommonAccountsBuilder {
	inst.AccountMetaSlice[4] = ag_solanago.Meta(reservePda).WRITE()
	return inst
}

// GetReservePdaAccount gets the "reservePda" account.
func (inst *UpdateDeactivatedCommonAccountsBuilder) GetReservePdaAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(4)
}

// SetMsolMintAccount sets the "msolMint" account.
func (inst *UpdateDeactivatedCommonAccountsBuilder) SetMsolMintAccount(msolMint ag_solanago.PublicKey) *UpdateDeactivatedCommonAccountsBuilder {
	inst.AccountMetaSlice[5] = ag_solanago.Meta(msolMint).WRITE()
	return inst
}

// GetMsolMintAccount gets the "msolMint" account.
func (inst *UpdateDeactivatedCommonAccountsBuilder) GetMsolMintAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(5)
}

// SetMsolMintAuthorityAccount sets the "msolMintAuthority" account.
func (inst *UpdateDeactivatedCommonAccountsBuilder) SetMsolMintAuthorityAccount(msolMintAuthority ag_solanago.PublicKey) *UpdateDeactivatedCommonAccountsBuilder {
	inst.AccountMetaSlice[6] = ag_solanago.Meta(msolMintAuthority)
	return inst
}

// GetMsolMintAuthorityAccount gets the "msolMintAuthority" account.
func (inst *UpdateDeactivatedCommonAccountsBuilder) GetMsolMintAuthorityAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(6)
}

// SetTreasuryMsolAccountAccount sets the "treasuryMsolAccount" account.
func (inst *UpdateDeactivatedCommonAccountsBuilder) SetTreasuryMsolAccountAccount(treasuryMsolAccount ag_solanago.PublicKey) *UpdateDeactivatedCommonAccountsBuilder {
	inst.AccountMetaSlice[7] = ag_solanago.Meta(treasuryMsolAccount).WRITE()
	return inst
}

// GetTreasuryMsolAccountAccount gets the "treasuryMsolAccount" account.
func (inst *UpdateDeactivatedCommonAccountsBuilder) GetTreasuryMsolAccountAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(7)
}

// SetClockAccount sets the "clock" account.
func (inst *UpdateDeactivatedCommonAccountsBuilder) SetClockAccount(clock ag_solanago.PublicKey) *UpdateDeactivatedCommonAccountsBuilder {
	inst.AccountMetaSlice[8] = ag_solanago.Meta(clock)
	return inst
}

// GetClockAccount gets the "clock" account.
func (inst *UpdateDeactivatedCommonAccountsBuilder) GetClockAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(8)
}

// SetStakeHistoryAccount sets the "stakeHistory" account.
func (inst *UpdateDeactivatedCommonAccountsBuilder) SetStakeHistoryAccount(stakeHistory ag_solanago.PublicKey) *UpdateDeactivatedCommonAccountsBuilder {
	inst.AccountMetaSlice[9] = ag_solanago.Meta(stakeHistory)
	return inst
}

// GetStakeHistoryAccount gets the "stakeHistory" account.
func (inst *UpdateDeactivatedCommonAccountsBuilder) GetStakeHistoryAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(9)
}

// SetStakeProgramAccount sets the "stakeProgram" account.
func (inst *UpdateDeactivatedCommonAccountsBuilder) SetStakeProgramAccount(stakeProgram ag_solanago.PublicKey) *UpdateDeactivatedCommonAccountsBuilder {
	inst.AccountMetaSlice[10] = ag_solanago.Meta(stakeProgram)
	return inst
}

// GetStakeProgramAccount gets the "stakeProgram" account.
func (inst *UpdateDeactivatedCommonAccountsBuilder) GetStakeProgramAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(10)
}

// SetTokenProgramAccount sets the "tokenProgram" account.
func (inst *UpdateDeactivatedCommonAccountsBuilder) SetTokenProgramAccount(tokenProgram ag_solanago.PublicKey) *UpdateDeactivatedCommonAccountsBuilder {
	inst.AccountMetaSlice[11] = ag_solanago.Meta(tokenProgram)
	return inst
}

// GetTokenProgramAccount gets the "tokenProgram" account.
func (inst *UpdateDeactivatedCommonAccountsBuilder) GetTokenProgramAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(11)
}

// SetOperationalSolAccountAccount sets the "operationalSolAccount" account.
func (inst *UpdateDeactivated) SetOperationalSolAccountAccount(operationalSolAccount ag_solanago.PublicKey) *UpdateDeactivated {
	inst.AccountMetaSlice[12] = ag_solanago.Meta(operationalSolAccount).WRITE()
	return inst
}

// GetOperationalSolAccountAccount gets the "operationalSolAccount" account.
func (inst *UpdateDeactivated) GetOperationalSolAccountAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(12)
}

// SetSystemProgramAccount sets the "systemProgram" account.
func (inst *UpdateDeactivated) SetSystemProgramAccount(systemProgram ag_solanago.PublicKey) *UpdateDeactivated {
	inst.AccountMetaSlice[13] = ag_solanago.Meta(systemProgram)
	return inst
}

// GetSystemProgramAccount gets the "systemProgram" account.
func (inst *UpdateDeactivated) GetSystemProgramAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(13)
}

func (inst UpdateDeactivated) Build() *Instruction {
	return &Instruction{BaseVariant: ag_binary.BaseVariant{
		Impl:   inst,
		TypeID: Instruction_UpdateDeactivated,
	}}
}

// ValidateAndBuild validates the instruction parameters and accounts;
// if there is a validation error, it returns the error.
// Otherwise, it builds and returns the instruction.
func (inst UpdateDeactivated) ValidateAndBuild() (*Instruction, error) {
	if err := inst.Validate(); err != nil {
		return nil, err
	}
	return inst.Build(), nil
}

func (inst *UpdateDeactivated) Validate() error {
	// Check whether all (required) parameters are set:
	{
		if inst.StakeIndex == nil {
			return errors.New("StakeIndex parameter is not set")
		}
	}

	// Check whether all (required) accounts are set:
	{
		if inst.AccountMetaSlice[0] == nil {
			return errors.New("accounts.CommonState is not set")
		}
		if inst.AccountMetaSlice[1] == nil {
			return errors.New("accounts.CommonStakeList is not set")
		}
		if inst.AccountMetaSlice[2] == nil {
			return errors.New("accounts.CommonStakeAccount is not set")
		}
		if inst.AccountMetaSlice[3] == nil {
			return errors.New("accounts.CommonStakeWithdrawAuthority is not set")
		}
		if inst.AccountMetaSlice[4] == nil {
			return errors.New("accounts.CommonReservePda is not set")
		}
		if inst.AccountMetaSlice[5] == nil {
			return errors.New("accounts.CommonMsolMint is not set")
		}
		if inst.AccountMetaSlice[6] == nil {
			return errors.New("accounts.CommonMsolMintAuthority is not set")
		}
		if inst.AccountMetaSlice[7] == nil {
			return errors.New("accounts.CommonTreasuryMsolAccount is not set")
		}
		if inst.AccountMetaSlice[8] == nil {
			return errors.New("accounts.CommonClock is not set")
		}
		if inst.AccountMetaSlice[9] == nil {
			return errors.New("accounts.CommonStakeHistory is not set")
		}
		if inst.AccountMetaSlice[10] == nil {
			return errors.New("accounts.CommonStakeProgram is not set")
		}
		if inst.AccountMetaSlice[11] == nil {
			return errors.New("accounts.CommonTokenProgram is not set")
		}
		if inst.AccountMetaSlice[12] == nil {
			return errors.New("accounts.OperationalSolAccount is not set")
		}
		if inst.AccountMetaSlice[13] == nil {
			return errors.New("accounts.SystemProgram is not set")
		}
	}
	return nil
}

func (inst *UpdateDeactivated) EncodeToTree(parent ag_treeout.Branches) {
	parent.Child(ag_format.Program(ProgramName, ProgramID)).
		//
		ParentFunc(func(programBranch ag_treeout.Branches) {
			programBranch.Child(ag_format.Instruction("UpdateDeactivated")).
				//
				ParentFunc(func(instructionBranch ag_treeout.Branches) {

					// Parameters of the instruction:
					instructionBranch.Child("Params[len=1]").ParentFunc(func(paramsBranch ag_treeout.Branches) {
						paramsBranch.Child(ag_format.Param("StakeIndex", *inst.StakeIndex))
					})

					// Accounts of the instruction:
					instructionBranch.Child("Accounts[len=14]").ParentFunc(func(accountsBranch ag_treeout.Branches) {
						accountsBranch.Child(ag_format.Meta("                 common/state", inst.AccountMetaSlice.Get(0)))
						accountsBranch.Child(ag_format.Meta("             common/stakeList", inst.AccountMetaSlice.Get(1)))
						accountsBranch.Child(ag_format.Meta("                 common/stake", inst.AccountMetaSlice.Get(2)))
						accountsBranch.Child(ag_format.Meta("common/stakeWithdrawAuthority", inst.AccountMetaSlice.Get(3)))
						accountsBranch.Child(ag_format.Meta("            common/reservePda", inst.AccountMetaSlice.Get(4)))
						accountsBranch.Child(ag_format.Meta("              common/msolMint", inst.AccountMetaSlice.Get(5)))
						accountsBranch.Child(ag_format.Meta("     common/msolMintAuthority", inst.AccountMetaSlice.Get(6)))
						accountsBranch.Child(ag_format.Meta("          common/treasuryMsol", inst.AccountMetaSlice.Get(7)))
						accountsBranch.Child(ag_format.Meta("                 common/clock", inst.AccountMetaSlice.Get(8)))
						accountsBranch.Child(ag_format.Meta("          common/stakeHistory", inst.AccountMetaSlice.Get(9)))
						accountsBranch.Child(ag_format.Meta("          common/stakeProgram", inst.AccountMetaSlice.Get(10)))
						accountsBranch.Child(ag_format.Meta("          common/tokenProgram", inst.AccountMetaSlice.Get(11)))
						accountsBranch.Child(ag_format.Meta("               operationalSol", inst.AccountMetaSlice.Get(12)))
						accountsBranch.Child(ag_format.Meta("                systemProgram", inst.AccountMetaSlice.Get(13)))
					})
				})
		})
}

func (obj UpdateDeactivated) MarshalWithEncoder(encoder *ag_binary.Encoder) (err error) {
	// Serialize `StakeIndex` param:
	err = encoder.Encode(obj.StakeIndex)
	if err != nil {
		return err
	}
	return nil
}
func (obj *UpdateDeactivated) UnmarshalWithDecoder(decoder *ag_binary.Decoder) (err error) {
	// Deserialize `StakeIndex`:
	err = decoder.Decode(&obj.StakeIndex)
	if err != nil {
		return err
	}
	return nil
}

// NewUpdateDeactivatedInstruction declares a new UpdateDeactivated instruction with the provided parameters and accounts.
func NewUpdateDeactivatedInstruction(
	// Parameters:
	stakeIndex uint32,
	// Accounts:
	commonState ag_solanago.PublicKey,
	commonStakeList ag_solanago.PublicKey,
	commonStakeAccount ag_solanago.PublicKey,
	commonStakeWithdrawAuthority ag_solanago.PublicKey,
	commonReservePda ag_solanago.PublicKey,
	commonMsolMint ag_solanago.PublicKey,
	commonMsolMintAuthority ag_solanago.PublicKey,
	commonTreasuryMsolAccount ag_solanago.PublicKey,
	commonClock ag_solanago.PublicKey,
	commonStakeHistory ag_solanago.PublicKey,
	commonStakeProgram ag_solanago.PublicKey,
	commonTokenProgram ag_solanago.PublicKey,
	operationalSolAccount ag_solanago.PublicKey,
	systemProgram ag_solanago.PublicKey) *UpdateDeactivated {
	return NewUpdateDeactivatedInstructionBuilder().
		SetStakeIndex(stakeIndex).
		SetCommonAccountsFromBuilder(
			NewUpdateDeactivatedCommonAccountsBuilder().
				SetStateAccount(commonState).
				SetStakeListAccount(commonStakeList).
				SetStakeAccountAccount(commonStakeAccount).
				SetStakeWithdrawAuthorityAccount(commonStakeWithdrawAuthority).
				SetReservePdaAccount(commonReservePda).
				SetMsolMintAccount(commonMsolMint).
				SetMsolMintAuthorityAccount(commonMsolMintAuthority).
				SetTreasuryMsolAccountAccount(commonTreasuryMsolAccount).
				SetClockAccount(commonClock).
				SetStakeHistoryAccount(commonStakeHistory).
				SetStakeProgramAccount(commonStakeProgram).
				SetTokenProgramAccount(commonTokenProgram),
		).
		SetOperationalSolAccountAccount(operationalSolAccount).
		SetSystemProgramAccount(systemProgram)
}
