// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.

package marinade_finance

import (
	"errors"
	ag_binary "github.com/gagliardetto/binary"
	ag_solanago "github.com/gagliardetto/solana-go"
	ag_format "github.com/gagliardetto/solana-go/text/format"
	ag_treeout "github.com/gagliardetto/treeout"
)

// WithdrawStakeAccount is the `withdrawStakeAccount` instruction.
type WithdrawStakeAccount struct {
	StakeIndex     *uint32
	ValidatorIndex *uint32
	MsolAmount     *uint64
	Beneficiary    *ag_solanago.PublicKey

	// [0] = [WRITE] state
	//
	// [1] = [WRITE] msolMint
	//
	// [2] = [WRITE] burnMsolFrom
	//
	// [3] = [WRITE, SIGNER] burnMsolAuthority
	//
	// [4] = [WRITE] treasuryMsolAccount
	//
	// [5] = [WRITE] validatorList
	//
	// [6] = [WRITE] stakeList
	//
	// [7] = [] stakeWithdrawAuthority
	//
	// [8] = [] stakeDepositAuthority
	//
	// [9] = [WRITE] stakeAccount
	//
	// [10] = [WRITE, SIGNER] splitStakeAccount
	//
	// [11] = [WRITE, SIGNER] splitStakeRentPayer
	//
	// [12] = [] clock
	//
	// [13] = [] systemProgram
	//
	// [14] = [] tokenProgram
	//
	// [15] = [] stakeProgram
	ag_solanago.AccountMetaSlice `bin:"-"`
}

// NewWithdrawStakeAccountInstructionBuilder creates a new `WithdrawStakeAccount` instruction builder.
func NewWithdrawStakeAccountInstructionBuilder() *WithdrawStakeAccount {
	nd := &WithdrawStakeAccount{
		AccountMetaSlice: make(ag_solanago.AccountMetaSlice, 16),
	}
	return nd
}

// SetStakeIndex sets the "stakeIndex" parameter.
func (inst *WithdrawStakeAccount) SetStakeIndex(stakeIndex uint32) *WithdrawStakeAccount {
	inst.StakeIndex = &stakeIndex
	return inst
}

// SetValidatorIndex sets the "validatorIndex" parameter.
func (inst *WithdrawStakeAccount) SetValidatorIndex(validatorIndex uint32) *WithdrawStakeAccount {
	inst.ValidatorIndex = &validatorIndex
	return inst
}

// SetMsolAmount sets the "msolAmount" parameter.
func (inst *WithdrawStakeAccount) SetMsolAmount(msolAmount uint64) *WithdrawStakeAccount {
	inst.MsolAmount = &msolAmount
	return inst
}

// SetBeneficiary sets the "beneficiary" parameter.
func (inst *WithdrawStakeAccount) SetBeneficiary(beneficiary ag_solanago.PublicKey) *WithdrawStakeAccount {
	inst.Beneficiary = &beneficiary
	return inst
}

// SetStateAccount sets the "state" account.
func (inst *WithdrawStakeAccount) SetStateAccount(state ag_solanago.PublicKey) *WithdrawStakeAccount {
	inst.AccountMetaSlice[0] = ag_solanago.Meta(state).WRITE()
	return inst
}

// GetStateAccount gets the "state" account.
func (inst *WithdrawStakeAccount) GetStateAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(0)
}

// SetMsolMintAccount sets the "msolMint" account.
func (inst *WithdrawStakeAccount) SetMsolMintAccount(msolMint ag_solanago.PublicKey) *WithdrawStakeAccount {
	inst.AccountMetaSlice[1] = ag_solanago.Meta(msolMint).WRITE()
	return inst
}

// GetMsolMintAccount gets the "msolMint" account.
func (inst *WithdrawStakeAccount) GetMsolMintAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(1)
}

// SetBurnMsolFromAccount sets the "burnMsolFrom" account.
func (inst *WithdrawStakeAccount) SetBurnMsolFromAccount(burnMsolFrom ag_solanago.PublicKey) *WithdrawStakeAccount {
	inst.AccountMetaSlice[2] = ag_solanago.Meta(burnMsolFrom).WRITE()
	return inst
}

// GetBurnMsolFromAccount gets the "burnMsolFrom" account.
func (inst *WithdrawStakeAccount) GetBurnMsolFromAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(2)
}

// SetBurnMsolAuthorityAccount sets the "burnMsolAuthority" account.
func (inst *WithdrawStakeAccount) SetBurnMsolAuthorityAccount(burnMsolAuthority ag_solanago.PublicKey) *WithdrawStakeAccount {
	inst.AccountMetaSlice[3] = ag_solanago.Meta(burnMsolAuthority).WRITE().SIGNER()
	return inst
}

// GetBurnMsolAuthorityAccount gets the "burnMsolAuthority" account.
func (inst *WithdrawStakeAccount) GetBurnMsolAuthorityAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(3)
}

// SetTreasuryMsolAccountAccount sets the "treasuryMsolAccount" account.
func (inst *WithdrawStakeAccount) SetTreasuryMsolAccountAccount(treasuryMsolAccount ag_solanago.PublicKey) *WithdrawStakeAccount {
	inst.AccountMetaSlice[4] = ag_solanago.Meta(treasuryMsolAccount).WRITE()
	return inst
}

// GetTreasuryMsolAccountAccount gets the "treasuryMsolAccount" account.
func (inst *WithdrawStakeAccount) GetTreasuryMsolAccountAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(4)
}

// SetValidatorListAccount sets the "validatorList" account.
func (inst *WithdrawStakeAccount) SetValidatorListAccount(validatorList ag_solanago.PublicKey) *WithdrawStakeAccount {
	inst.AccountMetaSlice[5] = ag_solanago.Meta(validatorList).WRITE()
	return inst
}

// GetValidatorListAccount gets the "validatorList" account.
func (inst *WithdrawStakeAccount) GetValidatorListAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(5)
}

// SetStakeListAccount sets the "stakeList" account.
func (inst *WithdrawStakeAccount) SetStakeListAccount(stakeList ag_solanago.PublicKey) *WithdrawStakeAccount {
	inst.AccountMetaSlice[6] = ag_solanago.Meta(stakeList).WRITE()
	return inst
}

// GetStakeListAccount gets the "stakeList" account.
func (inst *WithdrawStakeAccount) GetStakeListAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(6)
}

// SetStakeWithdrawAuthorityAccount sets the "stakeWithdrawAuthority" account.
func (inst *WithdrawStakeAccount) SetStakeWithdrawAuthorityAccount(stakeWithdrawAuthority ag_solanago.PublicKey) *WithdrawStakeAccount {
	inst.AccountMetaSlice[7] = ag_solanago.Meta(stakeWithdrawAuthority)
	return inst
}

// GetStakeWithdrawAuthorityAccount gets the "stakeWithdrawAuthority" account.
func (inst *WithdrawStakeAccount) GetStakeWithdrawAuthorityAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(7)
}

// SetStakeDepositAuthorityAccount sets the "stakeDepositAuthority" account.
func (inst *WithdrawStakeAccount) SetStakeDepositAuthorityAccount(stakeDepositAuthority ag_solanago.PublicKey) *WithdrawStakeAccount {
	inst.AccountMetaSlice[8] = ag_solanago.Meta(stakeDepositAuthority)
	return inst
}

// GetStakeDepositAuthorityAccount gets the "stakeDepositAuthority" account.
func (inst *WithdrawStakeAccount) GetStakeDepositAuthorityAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(8)
}

// SetStakeAccountAccount sets the "stakeAccount" account.
func (inst *WithdrawStakeAccount) SetStakeAccountAccount(stakeAccount ag_solanago.PublicKey) *WithdrawStakeAccount {
	inst.AccountMetaSlice[9] = ag_solanago.Meta(stakeAccount).WRITE()
	return inst
}

// GetStakeAccountAccount gets the "stakeAccount" account.
func (inst *WithdrawStakeAccount) GetStakeAccountAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(9)
}

// SetSplitStakeAccountAccount sets the "splitStakeAccount" account.
func (inst *WithdrawStakeAccount) SetSplitStakeAccountAccount(splitStakeAccount ag_solanago.PublicKey) *WithdrawStakeAccount {
	inst.AccountMetaSlice[10] = ag_solanago.Meta(splitStakeAccount).WRITE().SIGNER()
	return inst
}

// GetSplitStakeAccountAccount gets the "splitStakeAccount" account.
func (inst *WithdrawStakeAccount) GetSplitStakeAccountAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(10)
}

// SetSplitStakeRentPayerAccount sets the "splitStakeRentPayer" account.
func (inst *WithdrawStakeAccount) SetSplitStakeRentPayerAccount(splitStakeRentPayer ag_solanago.PublicKey) *WithdrawStakeAccount {
	inst.AccountMetaSlice[11] = ag_solanago.Meta(splitStakeRentPayer).WRITE().SIGNER()
	return inst
}

// GetSplitStakeRentPayerAccount gets the "splitStakeRentPayer" account.
func (inst *WithdrawStakeAccount) GetSplitStakeRentPayerAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(11)
}

// SetClockAccount sets the "clock" account.
func (inst *WithdrawStakeAccount) SetClockAccount(clock ag_solanago.PublicKey) *WithdrawStakeAccount {
	inst.AccountMetaSlice[12] = ag_solanago.Meta(clock)
	return inst
}

// GetClockAccount gets the "clock" account.
func (inst *WithdrawStakeAccount) GetClockAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(12)
}

// SetSystemProgramAccount sets the "systemProgram" account.
func (inst *WithdrawStakeAccount) SetSystemProgramAccount(systemProgram ag_solanago.PublicKey) *WithdrawStakeAccount {
	inst.AccountMetaSlice[13] = ag_solanago.Meta(systemProgram)
	return inst
}

// GetSystemProgramAccount gets the "systemProgram" account.
func (inst *WithdrawStakeAccount) GetSystemProgramAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(13)
}

// SetTokenProgramAccount sets the "tokenProgram" account.
func (inst *WithdrawStakeAccount) SetTokenProgramAccount(tokenProgram ag_solanago.PublicKey) *WithdrawStakeAccount {
	inst.AccountMetaSlice[14] = ag_solanago.Meta(tokenProgram)
	return inst
}

// GetTokenProgramAccount gets the "tokenProgram" account.
func (inst *WithdrawStakeAccount) GetTokenProgramAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(14)
}

// SetStakeProgramAccount sets the "stakeProgram" account.
func (inst *WithdrawStakeAccount) SetStakeProgramAccount(stakeProgram ag_solanago.PublicKey) *WithdrawStakeAccount {
	inst.AccountMetaSlice[15] = ag_solanago.Meta(stakeProgram)
	return inst
}

// GetStakeProgramAccount gets the "stakeProgram" account.
func (inst *WithdrawStakeAccount) GetStakeProgramAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(15)
}

func (inst WithdrawStakeAccount) Build() *Instruction {
	return &Instruction{BaseVariant: ag_binary.BaseVariant{
		Impl:   inst,
		TypeID: Instruction_WithdrawStakeAccount,
	}}
}

// ValidateAndBuild validates the instruction parameters and accounts;
// if there is a validation error, it returns the error.
// Otherwise, it builds and returns the instruction.
func (inst WithdrawStakeAccount) ValidateAndBuild() (*Instruction, error) {
	if err := inst.Validate(); err != nil {
		return nil, err
	}
	return inst.Build(), nil
}

func (inst *WithdrawStakeAccount) Validate() error {
	// Check whether all (required) parameters are set:
	{
		if inst.StakeIndex == nil {
			return errors.New("StakeIndex parameter is not set")
		}
		if inst.ValidatorIndex == nil {
			return errors.New("ValidatorIndex parameter is not set")
		}
		if inst.MsolAmount == nil {
			return errors.New("MsolAmount parameter is not set")
		}
		if inst.Beneficiary == nil {
			return errors.New("Beneficiary parameter is not set")
		}
	}

	// Check whether all (required) accounts are set:
	{
		if inst.AccountMetaSlice[0] == nil {
			return errors.New("accounts.State is not set")
		}
		if inst.AccountMetaSlice[1] == nil {
			return errors.New("accounts.MsolMint is not set")
		}
		if inst.AccountMetaSlice[2] == nil {
			return errors.New("accounts.BurnMsolFrom is not set")
		}
		if inst.AccountMetaSlice[3] == nil {
			return errors.New("accounts.BurnMsolAuthority is not set")
		}
		if inst.AccountMetaSlice[4] == nil {
			return errors.New("accounts.TreasuryMsolAccount is not set")
		}
		if inst.AccountMetaSlice[5] == nil {
			return errors.New("accounts.ValidatorList is not set")
		}
		if inst.AccountMetaSlice[6] == nil {
			return errors.New("accounts.StakeList is not set")
		}
		if inst.AccountMetaSlice[7] == nil {
			return errors.New("accounts.StakeWithdrawAuthority is not set")
		}
		if inst.AccountMetaSlice[8] == nil {
			return errors.New("accounts.StakeDepositAuthority is not set")
		}
		if inst.AccountMetaSlice[9] == nil {
			return errors.New("accounts.StakeAccount is not set")
		}
		if inst.AccountMetaSlice[10] == nil {
			return errors.New("accounts.SplitStakeAccount is not set")
		}
		if inst.AccountMetaSlice[11] == nil {
			return errors.New("accounts.SplitStakeRentPayer is not set")
		}
		if inst.AccountMetaSlice[12] == nil {
			return errors.New("accounts.Clock is not set")
		}
		if inst.AccountMetaSlice[13] == nil {
			return errors.New("accounts.SystemProgram is not set")
		}
		if inst.AccountMetaSlice[14] == nil {
			return errors.New("accounts.TokenProgram is not set")
		}
		if inst.AccountMetaSlice[15] == nil {
			return errors.New("accounts.StakeProgram is not set")
		}
	}
	return nil
}

func (inst *WithdrawStakeAccount) EncodeToTree(parent ag_treeout.Branches) {
	parent.Child(ag_format.Program(ProgramName, ProgramID)).
		//
		ParentFunc(func(programBranch ag_treeout.Branches) {
			programBranch.Child(ag_format.Instruction("WithdrawStakeAccount")).
				//
				ParentFunc(func(instructionBranch ag_treeout.Branches) {

					// Parameters of the instruction:
					instructionBranch.Child("Params[len=4]").ParentFunc(func(paramsBranch ag_treeout.Branches) {
						paramsBranch.Child(ag_format.Param("    StakeIndex", *inst.StakeIndex))
						paramsBranch.Child(ag_format.Param("ValidatorIndex", *inst.ValidatorIndex))
						paramsBranch.Child(ag_format.Param("    MsolAmount", *inst.MsolAmount))
						paramsBranch.Child(ag_format.Param("   Beneficiary", *inst.Beneficiary))
					})

					// Accounts of the instruction:
					instructionBranch.Child("Accounts[len=16]").ParentFunc(func(accountsBranch ag_treeout.Branches) {
						accountsBranch.Child(ag_format.Meta("                 state", inst.AccountMetaSlice.Get(0)))
						accountsBranch.Child(ag_format.Meta("              msolMint", inst.AccountMetaSlice.Get(1)))
						accountsBranch.Child(ag_format.Meta("          burnMsolFrom", inst.AccountMetaSlice.Get(2)))
						accountsBranch.Child(ag_format.Meta("     burnMsolAuthority", inst.AccountMetaSlice.Get(3)))
						accountsBranch.Child(ag_format.Meta("          treasuryMsol", inst.AccountMetaSlice.Get(4)))
						accountsBranch.Child(ag_format.Meta("         validatorList", inst.AccountMetaSlice.Get(5)))
						accountsBranch.Child(ag_format.Meta("             stakeList", inst.AccountMetaSlice.Get(6)))
						accountsBranch.Child(ag_format.Meta("stakeWithdrawAuthority", inst.AccountMetaSlice.Get(7)))
						accountsBranch.Child(ag_format.Meta(" stakeDepositAuthority", inst.AccountMetaSlice.Get(8)))
						accountsBranch.Child(ag_format.Meta("                 stake", inst.AccountMetaSlice.Get(9)))
						accountsBranch.Child(ag_format.Meta("            splitStake", inst.AccountMetaSlice.Get(10)))
						accountsBranch.Child(ag_format.Meta("   splitStakeRentPayer", inst.AccountMetaSlice.Get(11)))
						accountsBranch.Child(ag_format.Meta("                 clock", inst.AccountMetaSlice.Get(12)))
						accountsBranch.Child(ag_format.Meta("         systemProgram", inst.AccountMetaSlice.Get(13)))
						accountsBranch.Child(ag_format.Meta("          tokenProgram", inst.AccountMetaSlice.Get(14)))
						accountsBranch.Child(ag_format.Meta("          stakeProgram", inst.AccountMetaSlice.Get(15)))
					})
				})
		})
}

func (obj WithdrawStakeAccount) MarshalWithEncoder(encoder *ag_binary.Encoder) (err error) {
	// Serialize `StakeIndex` param:
	err = encoder.Encode(obj.StakeIndex)
	if err != nil {
		return err
	}
	// Serialize `ValidatorIndex` param:
	err = encoder.Encode(obj.ValidatorIndex)
	if err != nil {
		return err
	}
	// Serialize `MsolAmount` param:
	err = encoder.Encode(obj.MsolAmount)
	if err != nil {
		return err
	}
	// Serialize `Beneficiary` param:
	err = encoder.Encode(obj.Beneficiary)
	if err != nil {
		return err
	}
	return nil
}
func (obj *WithdrawStakeAccount) UnmarshalWithDecoder(decoder *ag_binary.Decoder) (err error) {
	// Deserialize `StakeIndex`:
	err = decoder.Decode(&obj.StakeIndex)
	if err != nil {
		return err
	}
	// Deserialize `ValidatorIndex`:
	err = decoder.Decode(&obj.ValidatorIndex)
	if err != nil {
		return err
	}
	// Deserialize `MsolAmount`:
	err = decoder.Decode(&obj.MsolAmount)
	if err != nil {
		return err
	}
	// Deserialize `Beneficiary`:
	err = decoder.Decode(&obj.Beneficiary)
	if err != nil {
		return err
	}
	return nil
}

// NewWithdrawStakeAccountInstruction declares a new WithdrawStakeAccount instruction with the provided parameters and accounts.
func NewWithdrawStakeAccountInstruction(
	// Parameters:
	stakeIndex uint32,
	validatorIndex uint32,
	msolAmount uint64,
	beneficiary ag_solanago.PublicKey,
	// Accounts:
	state ag_solanago.PublicKey,
	msolMint ag_solanago.PublicKey,
	burnMsolFrom ag_solanago.PublicKey,
	burnMsolAuthority ag_solanago.PublicKey,
	treasuryMsolAccount ag_solanago.PublicKey,
	validatorList ag_solanago.PublicKey,
	stakeList ag_solanago.PublicKey,
	stakeWithdrawAuthority ag_solanago.PublicKey,
	stakeDepositAuthority ag_solanago.PublicKey,
	stakeAccount ag_solanago.PublicKey,
	splitStakeAccount ag_solanago.PublicKey,
	splitStakeRentPayer ag_solanago.PublicKey,
	clock ag_solanago.PublicKey,
	systemProgram ag_solanago.PublicKey,
	tokenProgram ag_solanago.PublicKey,
	stakeProgram ag_solanago.PublicKey) *WithdrawStakeAccount {
	return NewWithdrawStakeAccountInstructionBuilder().
		SetStakeIndex(stakeIndex).
		SetValidatorIndex(validatorIndex).
		SetMsolAmount(msolAmount).
		SetBeneficiary(beneficiary).
		SetStateAccount(state).
		SetMsolMintAccount(msolMint).
		SetBurnMsolFromAccount(burnMsolFrom).
		SetBurnMsolAuthorityAccount(burnMsolAuthority).
		SetTreasuryMsolAccountAccount(treasuryMsolAccount).
		SetValidatorListAccount(validatorList).
		SetStakeListAccount(stakeList).
		SetStakeWithdrawAuthorityAccount(stakeWithdrawAuthority).
		SetStakeDepositAuthorityAccount(stakeDepositAuthority).
		SetStakeAccountAccount(stakeAccount).
		SetSplitStakeAccountAccount(splitStakeAccount).
		SetSplitStakeRentPayerAccount(splitStakeRentPayer).
		SetClockAccount(clock).
		SetSystemProgramAccount(systemProgram).
		SetTokenProgramAccount(tokenProgram).
		SetStakeProgramAccount(stakeProgram)
}
